pipeline {
    agent any

     environment {
        CI = 'true'
    }
    stages {

        stage('Development Branch'){
            when {
               branch: 'development' value: 'yes'
            }
            steps{
                script{
                    docker.build('jenkins/demo','/var/www/workspace/JenkinsDemo/service1/')
                }
            }
        }
        stage('Master Branch'){
            when {
               branch: 'master' value: 'yes'
            }
            steps{
                script{
                    docker.build('jenkins/demo','/var/www/workspace/JenkinsDemo/service1/')
                }
            }
        }        

        stage('Docker push'){
            steps{
                script{
                    docker.withRegistry('https://943112551667.dkr.ecr.ap-south-1.amazonaws.com', 'ecr:ap-south-1:amazon-dev') {
                        docker.image('jenkins/demo').push("$currentBuild.number")
                    }
                }
            }
        }
    }
}